<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class User extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
//        return parent::toArray($request);
        return [
            'name' => $this->name,
            'email' => $this->email
        ];
    }

    public function with($request)
    {
        return [
            'version' => 2,
            'md5' => md5(json_encode(parent::toArray($request)))
        ];
        //return parent::with($request); // TODO: Change the autogenerated stub
    }
}
